"""initial migration

Revision ID: 3bdd0aa05420
Revises: 
Create Date: 2023-06-20 18:57:02.163501

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3bdd0aa05420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_stat',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('channel', sa.String(), nullable=False),
                    sa.Column('country', sa.String(), nullable=False),
                    sa.Column('os', sa.String(), nullable=False),
                    sa.Column('impressions', sa.Integer(), nullable=False),
                    sa.Column('clicks', sa.Integer(), nullable=False),
                    sa.Column('installs', sa.Integer(), nullable=False),
                    sa.Column('spend', sa.Numeric(), nullable=False),
                    sa.Column('revenue', sa.Numeric(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_campaign_stat_id'), 'campaign_stat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_stat_id'), table_name='campaign_stat')
    op.drop_table('campaign_stat')
    # ### end Alembic commands ###
